{{- if .Values.applicationDefaultConfig.sharedNamespace.create }}
{{- $organization_id := include "common.tplvalues.render" (dict "value" $.Values.global.additionalLabels.organization_id "context" $) }}
{{- $environment := include "common.tplvalues.render" (dict "value" $.Values.global.additionalLabels.environment "context" $) }}
{{- $quest_code := include "common.tplvalues.render" (dict "value" $.Values.global.additionalLabels.quest_code "context" $) }}
---
apiVersion: v1
kind: Namespace
metadata:
  {{- if .Values.applicationDefaultConfig.sharedNamespace.name }}
  name: {{ .Values.applicationDefaultConfig.sharedNamespace.name }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.applicationDefaultConfig.sharedNamespace.name }}
    app: {{ .Values.applicationDefaultConfig.sharedNamespace.name }}
  {{- else }}
  name: {{ printf "%s-%s-%s" $organization_id $quest_code $environment }}
  labels:
    kubernetes.io/metadata.name: {{ printf "%s-%s-%s" $organization_id $quest_code $environment }}
    app: {{ printf "%s-%s-%s" $organization_id $quest_code $environment }}
  {{- end }}
  {{- if .Values.applicationDefaultConfig.sharedNamespace.addLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.applicationDefaultConfig.sharedNamespace.addLabels "context" $) | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.additionalLabels  }}
    {{- include "common.tplvalues.render" (dict "value" $.Values.global.additionalLabels "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.applicationDefaultConfig.sharedNamespace.addAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.applicationDefaultConfig.sharedNamespace.addAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  finalizers:
    - kubernetes
{{- else }}
{{- $dot := . -}}
{{- range $applicationIndex, $application := .Values.applicationList }}
{{- if and $application.namespace.create (eq $application.namespace.method "helm") }}
{{- $organization_id := default (include "common.tplvalues.render" (dict "value" $.Values.global.additionalLabels.organization_id "context" $)) $application.labels.organization_id }}
{{- $environment := default (include "common.tplvalues.render" (dict "value" $.Values.global.additionalLabels.environment "context" $)) $application.labels.environment }}
{{- $quest_code := default (include "common.tplvalues.render" (dict "value" $.Values.global.additionalLabels.quest_code "context" $)) $application.labels.quest_code }}
---
apiVersion: v1
kind: Namespace
metadata:
  {{- if $application.namespace.name }}
  name: {{ $application.namespace.name }}
  {{- else if eq $quest_code $.Values.applicationDefaultConfig.initialApplicationGroup }}
  name: {{ $application.name }}
  {{- else }}
  name: {{ printf "%s-%s-%s-%s" $organization_id $quest_code $application.name $environment }}
  {{- end }}
  labels:
    kubernetes.io/metadata.name: {{ $application.name }}
    app: {{ $application.name }}
    {{- if $application.labels }}
      {{- include "common.tplvalues.render" (dict "value" $application.labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if $application.namespace.addLabels }}
      {{- include "common.tplvalues.render" (dict "value" $application.namespace.addLabels "context" $) | nindent 4 }}
    {{- end }}
    {{- if $.Values.global.additionalLabels  }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.global.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if $application.namespace.addAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $application.namespace.addAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  finalizers:
    - kubernetes
{{- end }}
{{- end -}}
{{- end }}
